### ISSUE TITLE
Bug in from_float for float images

### ISSUE THREAD

**Issue by rakhil575** [albumentations-team/albucore#29]
`rint` in `from_float` is incorrectly resulting in binary values for float images with values [0,1]

https://github.com/albumentations-team/albucore/blob/main/albucore/functions.py#L580
https://github.com/albumentations-team/albucore/blob/main/albucore/functions.py#L598

**Comment by ternaus** [comment]
Thanks, will take a look ASAP

**Comment by ternaus** [comment]
@rakhil575 

Could you please provide a few examples, so that I could add more relevant tests?

**Comment by rakhil575** [comment]
```
from albucore.functions import from_float, to_float

test_image = np.random.rand(2,2).astype(np.float32)
print(test_image.dtype)
print(test_image)

image_to_float = to_float(test_image)
print(image_to_float)

image_from_float = from_float(image_to_float, np.float32)
print(image_from_float)
```

![image](https://github.com/user-attachments/assets/ae2abeb2-b4ad-4597-834b-b86fe2350281)

**Comment by rakhil575** [comment]
I was particularly using the Spatter augmentation. It's working for uint8 images but not for float images

**Comment by ternaus** [comment]
```python
In [3]: from albucore.functions import from_float, to_float
   ...:
   ...: test_image = np.random.rand(2,2).astype(np.float32)
   ...: print(test_image.dtype)
   ...: print(test_image)
   ...:
   ...: image_to_float = to_float(test_image)
   ...: print(image_to_float)
   ...:
   ...: image_from_float = from_float(image_to_float, np.uint8)
   ...: print(image_from_float)
float32
[[0.07755405 0.55121404]
 [0.5198594  0.3250532 ]]
[[0.07755405 0.55121404]
 [0.5198594  0.3250532 ]]
[[ 20 141]
 [133  83]]
```

From_float works as expected. But I will look into Spatter

**Comment by ternaus** [comment]
You are right, it is a bug.

`from_float(img, float32)` should return `image`

**Comment by ternaus** [comment]
FIxws

**Comment by rakhil575** [comment]
Awesome, thanks!

**Comment by ternaus** [comment]
You may check it out at https://explore.albumentations.ai/transform/Spatter
