### ISSUE TITLE
Import Error on albucore 0.0.17

### ISSUE THREAD

**Issue by W1ls0nG0** [albumentations-team/albucore#33]
Exception has occurred: ImportError
cannot import name 'preserve_channel_dim' from 'albucore.utils' (/home/user/.pyenv/versions/general/lib/python3.11/site-packages/albucore/utils.py)

Exception happened when trying to import albumentations. 0.0.15 work fine.

environment: python3.11.10

**Comment by myhloli** [comment]
same error with me.

**Comment by samedii** [comment]
Downgrading worked for me.

albucore = "^0.0.16"

**Comment by cyborghunt** [comment]
> Downgrading worked for me.
> 
> albucore = "^0.0.16"

hey man can u tell what exactly you did that helped i have been trying for a good while nothing seems to work

**Comment by wclemonade** [comment]
> > Downgrading worked for me.
> > albucore = "^0.0.16"
> 
> hey man can u tell what exactly you did that helped i have been trying for a good while nothing seems to work
just   pip install -U albucore==0.0.16

**Comment by cyborghunt** [comment]
thanks for the help brother

**Comment by ternaus** [comment]
Released version 1.4.16 of albumentations. Works correcly with albucore 0.0.17
